name: Run Appium Tests on BrowserStack

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      BS_USER_NAME: ${{ secrets.BS_USER_NAME }}
      BS_ACCESS_KEY: ${{ secrets.BS_ACCESS_KEY }}
      BS_APP_ID: ${{ secrets.BS_APP_ID }}
    name: Run Appium Tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run All Tests
        if: "github.event.inputs.deployment_target == 'all_tests'"
        run: |
          pytest --alluredir=allure-results

      - name: Run Create Tests
        if: "github.event.inputs.deployment_target == 'create_tests'"
        run: |
          pytest tests/create --alluredir=allure-results

      - name: Run Delete Tests
        if: "github.event.inputs.deployment_target == 'delete_tests'"
        run: |
          pytest tests/delete --alluredir=allure-results

      - name: Run Edit Tests
        if: "github.event.inputs.deployment_target == 'edit_tests'"
        run: |
          pytest tests/edit --alluredir=allure-results

      - name: Run View Tests
        if: "github.event.inputs.deployment_target == 'view_tests'"
        run: |
          pytest tests/view --alluredir=allure-results

      - name: Run Failed Tests
        if: "github.event.inputs.deployment_target == 'failed_tests'"
        run: |
          pytest tests/failed --alluredir=allure-results

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
