name: Run Appium Tests on BrowserStack

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select tests to run
        required: true
        default:
        type: choice
        options:
          - all_tests
          - create_tests
          - delete_tests
          - edit_tests
          - view_tests
          - failed_tests

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      BS_USER_NAME: ${{ secrets.BS_USER_NAME }}
      BS_ACCESS_KEY: ${{ secrets.BS_ACCESS_KEY }}
      BS_APP_ID: ${{ secrets.BS_APP_ID }}
    name: Run Appium Tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run All Tests
        if: "github.event.inputs.deployment_target == 'all_tests'"
        run: |
          pytest --alluredir=allure-results
        continue-on-error: true

      - name: Run Create Tests
        if: "github.event.inputs.deployment_target == 'create_tests'"
        run: |
          pytest src/tests/create --alluredir=allure-results
        continue-on-error: true

      - name: Run Delete Tests
        if: "github.event.inputs.deployment_target == 'delete_tests'"
        run: |
          pytest src/tests/delete --alluredir=allure-results
        continue-on-error: true

      - name: Run Edit Tests
        if: "github.event.inputs.deployment_target == 'edit_tests'"
        run: |
          pytest src/tests/edit --alluredir=allure-results
        continue-on-error: true

      - name: Run View Tests
        if: "github.event.inputs.deployment_target == 'view_tests'"
        run: |
          pytest src/tests/view --alluredir=allure-results
        continue-on-error: true

      - name: Run Failed Tests
        if: "github.event.inputs.deployment_target == 'failed_tests'"
        run: |
          pytest src/tests/failed --alluredir=allure-results
        continue-on-error: true

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
